### PR TITLE
test for shadow of shadow Signal

### PR DESCRIPTION
**Pull request by udara28**
Added file test_ShadowOfShadowSignal.py which contains two tests. One for testing slicing a sliced signal. Other for concat a concatenated signal.

### CODE REVIEW

**Comment by udara28** [comment]
Instead of adding a new file test_ShadowOfShadowSignal.py, Additional tests were added to the same test_ShadowSignal.py file. New test_ShadowSignal.py file contains 5 tests now.

**Comment by cfelton** [comment]
@udara28 thanks for contributing to the project and fixing an error.

Typically, we want to create separate pull-requests for different issues, in this case:

1. shadow-of-shadow tests (this will be useful as a regression if #52 is addressed).
2. invalid simulator configuration/registration.

A common git workflow is to create branches for new features and bugs:

```
>> git clone <your github fork>
>> git checkout -b new_test
```

On the branch, `new_test`, the new shadow-of-shadow test can be added.  And then, when you came across the bug create a different branch to implement the fix and submit a PR, example (the following has a couple extra steps to sync with the upstream, the main repo, if needed):

```
>> git checkout master        # switch back to the master branch
>> git remote add upstream https://github.com/jandecaluwe/myhdl
>> git pull upstream master  # syncs the master with the latest
>> git checkout -b bug_simconfig
```
At this point you have a new branch that is sync'd with the latest and you can implement the bug fix and push to your repo (git will inform how to push and create a branch to `origin`).  Github will prompt to create a PR from the new branch.  This keeps things nice and separate.  Github will even prompt to close a branch once a PR is merged.

There are others who are more savvy with git than I am, hopefully they will comment if the above is not ideal.

**Comment by udara28** [comment]
@cfelton  thank you very much for the valuable details. I made an error while making this PR. I did the changes in the master branch and create the PR. I understood the error when I tried to create a new PR for fixing simulator issue. Can I try the following to fix this right or is there a better way?

1. Create a new branch for test_ShadowSignal which will have the same changes.
2. Close this pull request and create a new PR from the new branch
3. revert the commits I have done to master branch.

**Comment by cfelton** [comment]
@udara28 , yes creating a branch and a new PR for the test would be great.  What you can do is (small modification to the steps you outlined):

1. sync the master (this will pick up the merged parts)
2. create the branch (it will have your test changes)
3. switch to the branch (`git checkout <branch>`)
4. verify the tests still work on the branch
5. push the branch to your Github fork
6. create the new PR for the test on the branch
7. in the local working directory, switch back to `master` and revert `test_ShadowSignals.py`

**Comment by udara28** [comment]
I'm closing this pull request to create a new one with the changes.

**Pull request closed without merging**
