### PR TITLE
Change format of README to markdown.

### PR DESCRIPTION
**Pull request by javValverde**
Add badges for docs and build (continuous integration)

### CODE REVIEW

**Comment by jandecaluwe** [comment]
Why refer to @jck 's travis account?

**Comment by javValverde** [comment]
I wasn't aware that you also had an account on travis. That should be changed.
I am on my way on setting an account on landscape.io. I want to add a badge to the README, but I guess you should have an account. You might be interested in checking it as well
Another idea is to use Coveralls.io (for code coverage), but that needs a little more work.

**Comment by jandecaluwe** [comment]
What is landscape.io?

**Comment by javValverde** [comment]
If I understand it correctly it is a web interface for prospector:
"It brings together the functionality of other Python analysis tools such as pylint, pep8 and McCabe complexity"

It basically makes static code analysis, and displays it in a nice way. Similar to travis, it is really to easy to integrate it in Github

**Comment by jandecaluwe** [comment]
If you refer to my account on travis (jandecaluwe) I will merge this in

**Pull request merged**
