### PR TITLE
Added operation tests for modbv

### PR DESCRIPTION
**Pull request by mwingerson**
Tests Added: Add, Subtract, Multiply, True Divide, Floor Divide, Power, Left shift, Right shift, And, Or and Xor

### CODE REVIEW

**Comment by mwingerson** [comment]
Adding more operations tests to increase testing coverage for the modbv class.

**Comment by jandecaluwe** [comment]
It seems this is just cut and paste from the `intbv` tests - it doesn't even test `modbv`! Tests for the `modbv` subclass may be meaningful, but duplicating code is not acceptable - some way to factor out identical code is mandatory.

**Comment by mwingerson** [comment]
My apologies, I was trying to submit a patch by the MyHDL deadline and those were the suggestions given to me.  I am very new to python and could not submit much more meaningful code then copying from what I could understand from the inbv class.  I would like the opportunity to produce a more substantial patch to modbv after I have learned more python.

My primary knowledge is in C.  Do you know a good resource to for learning the python testing infrastructure?

**Comment by cfelton** [comment]
@mwingerson if you Google "getting started with Python" or "Python tutorials" you will find many resources.  The [MyHDL GSoC project page](http://dev.myhdl.org/gsoc/gsoc_2015.html) has information to get started with MyHDL (you should be familiar with this page).

@mwingerson the goal was to increase the test coverage, the current test coverage for the `modbv` is:

```
Name                       Stmts   Miss  Cover   Missing
-------------------------------------------------------
myhdl/_modbv                 31     10    68%   36, 49, 53-62
```

@mwingerson ideally you would of had time to work with the mentors before submitting the PR like you did with the GSoC proposal (@tenthousandfailures).  It happens we are all learning the process.

The above coverage report also indicates the lines in `_modbv.py` that were not exercised.  If you replace the tests you added with tests to exercise the `modbv` indexing the tests will be useful.

**Comment by jandecaluwe** [comment]
@cfelton For my info, how do you determine the test coverage?

**Comment by cfelton** [comment]
@jandecaluwe We are using the Python coverage (`pip install coverage`).  I run the various tests separately and then combine the results (haven't perfected this approach yet, just looking at `test/core` and `test/core2`).

This is the setup of commands used to generate coverage info.
```
coverage:
	cd core && coverage run --source myhdl test_all.py
	cp core/.coverage .coverage.core1
	cd core2 && coverage run --source myhdl -m py.test
	cp core2/.coverage .coverage.core2
	coverage combine
	coverage report
	coverage report --show-missing
```

**Comment by mwingerson** [comment]
Hello Chris,

Sorry for the delay.  I really needed to take the weekend for my mental
health and to study for an exam.

Is there a good time for me to meet you on IRC?

Thanks,
Marshall

**Pull request closed without merging**
